import { describe, expect, it } from "vitest";

import {
  GENERATE_LOCKFILE_HINT,
  PINNED_CRATES_MARKER,
  formatMsrvLine,
  formatPinnedCratesBlock,
  parseCargoDirectDepNames,
  parseCargoLockVersions,
  parseRustToolchain,
  resolvePinnedCrates,
} from "./cargoCard";

const TOML = `[package]
name = "demo"
edition = "2024"
rust-version = "1.98.1"

[dependencies]
serde = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
`;

const LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tempfile"
version = "3.13.0"

[[package]]
name = "tokio"
version = "1.40.0"
`;

describe("parseCargoDirectDepNames", () => {
  it("reads dependencies, inline tables, and workspace deps", () => {
    expect(parseCargoDirectDepNames(TOML)).toEqual(
      expect.arrayContaining(["serde", "tokio", "tempfile"]),
    );
    expect(
      parseCargoDirectDepNames(`
[workspace.dependencies]
axum = "0.7"
`),
    ).toEqual(["axum"]);
  });
});

describe("parseCargoLockVersions", () => {
  it("keeps the first resolved version per crate", () => {
    const versions = parseCargoLockVersions(LOCK);
    expect(versions.get("serde")).toBe("1.0.210");
    expect(versions.get("tokio")).toBe("1.40.0");
    expect(versions.get("tempfile")).toBe("3.13.0");
  });
});

describe("resolvePinnedCrates / formatPinnedCratesBlock", () => {
  it("pairs direct deps with lock versions", () => {
    const { crates, hasLock } = resolvePinnedCrates(TOML, LOCK);
    expect(hasLock).toBe(true);
    expect(crates).toEqual([
      { name: "serde", version: "1.0.210" },
      { name: "tempfile", version: "3.13.0" },
      { name: "tokio", version: "1.40.0" },
    ]);
    const block = formatPinnedCratesBlock(TOML, LOCK);
    expect(block).toContain(PINNED_CRATES_MARKER);
    expect(block).toContain("serde 1.0.210");
    expect(block).toContain("tokio 1.40.0");
    expect(block).not.toContain("^");
  });

  it("does not invent versions when Cargo.lock is missing", () => {
    const { crates, hasLock } = resolvePinnedCrates(TOML, undefined);
    expect(hasLock).toBe(false);
    expect(crates).toEqual([]);
    expect(formatPinnedCratesBlock(TOML)).toContain(GENERATE_LOCKFILE_HINT);
    expect(formatPinnedCratesBlock(TOML)).not.toMatch(/1\.0\.210|axum 0\.6/);
  });
});

describe("parseRustToolchain / formatMsrvLine", () => {
  it("reads channel from rust-toolchain.toml", () => {
    expect(
      parseRustToolchain(`[toolchain]\nchannel = "1.76.0"\n`),
    ).toEqual({ channel: "1.76.0" });
    expect(parseRustToolchain("1.76.0\n")).toEqual({ channel: "1.76.0" });
    expect(parseRustToolchain("stable\n")).toEqual({ channel: "stable" });
  });

  it("mentions channel and package.rust-version", () => {
    const line = formatMsrvLine({
      rustVersion: "1.76",
      toolchainChannel: "1.76.0",
    });
    expect(line).toMatch(/channel 1\.76\.0/);
    expect(line).toMatch(/package\.rust-version 1\.76/);
    expect(line).toMatch(/do not append \+nightly/i);
  });
});
