// Common directories and file types to ignore when walking directories
export const DEFAULT_IGNORE_DIRS = [
  "node_modules",
  ".git",
  ".svn",
  ".hg",
  "dist",
  "build",
  "out",
  "target",
  "bin",
  "obj",
  "coverage",
  ".next",
  ".nuxt",
  ".vscode",
  ".idea",
  "__pycache__",
  ".pytest_cache",
  "venv",
  ".venv",
  "env",
  ".env"
];

export const DEFAULT_IGNORE_FILETYPES = [
  ".log",
  ".tmp",
  ".temp",
  ".cache",
  ".DS_Store",
  ".git",
  ".svn",
  ".hg",
  ".lock",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  ".min.js",
  ".min.css",
  ".map",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".o",
  ".obj",
  ".ko",
  ".dtb",
  ".dtbo",
  ".mod.c",
  ".cmd",
  ".pyc",
  ".pyo",
  ".class",
  ".jar",
  ".war",
  ".ear"
];

/** Kernel/QEMU artifacts with no reliable extension (HL-19 leftover). */
export const DEFAULT_IGNORE_BASENAMES = [
  "vmlinux",
  "vmlinux.bin",
  "System.map",
  "Module.symvers",
  "modules.order",
  "modules.builtin",
];
